services:
  backend:
    build: ./backend
    container_name: mlops_cv_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - AI_SERVICE_BASE_URL=http://face_service:8001
    depends_on:
      - face_service
    restart: unless-stopped

  face_service:
    build: ./face_service
    container_name: mlops_cv_ai_service
    ports:
      - "8001:8001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
    container_name: mlops_cv_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
